#!/usr/bin/env python3
"""Emit a hash-pinned requirements file for the panda firmware toolchain.

Versions and hashes come from the root ``uv.lock`` (upstream-owned), so the fork builds firmware
with exactly the toolchain the upstream tree pins, and a resync picks up toolchain bumps for free.
Install the output with ``uv pip install --require-hashes -r <file>``.
"""
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PACKAGES = ("scons", "comma-deps-gcc-arm-none-eabi")


def main() -> int:
  lock = tomllib.loads((ROOT / "uv.lock").read_text())
  by_name = {p["name"]: p for p in lock["package"]}
  lines = ["# generated by fork/scripts/fw_requirements.py from uv.lock; do not edit"]
  for name in PACKAGES:
    pkg = by_name.get(name)
    if pkg is None:
      print(f"error: {name} not found in uv.lock", file=sys.stderr)
      return 1
    artifacts = list(pkg.get("wheels", []))
    if "sdist" in pkg:
      artifacts.append(pkg["sdist"])
    hashes = sorted({a["hash"] for a in artifacts if "hash" in a})
    if not hashes:
      print(f"error: {name} has no hashes in uv.lock", file=sys.stderr)
      return 1
    lines.append(f"{name}=={pkg['version']} \\")
    lines.extend(f"    --hash={h} \\" for h in hashes[:-1])
    lines.append(f"    --hash={hashes[-1]}")
  print("\n".join(lines))
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
