#!/usr/bin/env bash
# Run the fork's openpilot-side Python tests on an x86_64 host.
#
# The prebuilt branch only ships aarch64 native libraries, so `import openpilot.common.params` fails on a PC
# (libparams_c.so is ARM). This script builds a host copy of libparams_c.so from the committed C++ sources
# (params_c.cc, params.cc, util.cc) into a cache dir OUTSIDE the tree, then runs pytest with a
# sitecustomize that points ctypes at that copy. Nothing native is written into the repo (invariant §2.2).
#
# Two pieces of the real build are not shipped on a prebuilt branch and are generated here instead:
#   * swaglog: params.cc/util.cc only call cloudlog_e(); a stub prints to stderr.
#   * cereal C++ headers: params_keys.h uses exactly one symbol, cereal::LongitudinalPersonality. Its
#     values are read from openpilot/cereal/log.capnp, and the build refuses to continue if
#     params_keys.h starts using any other cereal symbol.
#
# Usage: fork/scripts/py_tests.sh [pytest args...]   (TESTS below are used unless a test path is given)
# Env:   FORK_PY        python to use (default: a venv built from fork/scripts/py_test_requirements.txt)
#        FORK_PY_VENV   where that venv lives (default: ~/.cache/r1-fork/py-test-venv)
#        FORK_HOST_LIB  cache dir for the host build (default: ~/.cache/r1-fork/host-native)
set -euo pipefail

REPO="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
cd "$REPO"

TESTS=(
  openpilot/sunnypilot/selfdrive/car/tests/test_rivian_gear_disengage_sp.py
  openpilot/sunnypilot/selfdrive/car/tests/test_rivian_mads_steering_default_sp.py
  openpilot/sunnypilot/selfdrive/car/tests/test_rivian_b5b_sp.py
  openpilot/sunnypilot/selfdrive/car/tests/test_rivian_vehicle_gate_sp.py
  openpilot/sunnypilot/mads/tests  # upstream MADS tests: cover the helpers.py change
)

PY="${FORK_PY:-}"
if [[ -z "$PY" ]]; then
  command -v uv >/dev/null || { echo "error: uv is required (see CONTRIBUTING.md)" >&2; exit 2; }
  VENV="${FORK_PY_VENV:-$HOME/.cache/r1-fork/py-test-venv}"
  [[ -x "$VENV/bin/python" ]] || uv venv -q --python 3.12 "$VENV"
  VIRTUAL_ENV="$VENV" uv pip install -q --require-hashes -r "$REPO/fork/scripts/py_test_requirements.txt"
  PY="$VENV/bin/python"
fi

SRCS=(openpilot/common/params_c.cc openpilot/common/params.cc openpilot/common/util.cc)
HDRS=(openpilot/common/params.h openpilot/common/params_keys.h openpilot/common/util.h openpilot/common/swaglog.h
      openpilot/common/queue.h openpilot/common/timing.h openpilot/cereal/log.capnp)
MSGQ_SRCS=(msgq/ipc_pyx.cpp msgq/ipc.cc msgq/event.cc msgq/impl_fake.cc msgq/impl_msgq.cc msgq/msgq.cc)
KEY="$(cat "${SRCS[@]}" "${HDRS[@]}" "${MSGQ_SRCS[@]}" msgq/*.h "${BASH_SOURCE[0]}" | sha256sum | cut -c1-16)"
OUT="${FORK_HOST_LIB:-$HOME/.cache/r1-fork/host-native}/$KEY"
LIB="$OUT/libparams_c.so"

if [[ ! -f "$LIB" ]]; then
  echo "building host libparams_c.so -> $OUT"
  mkdir -p "$OUT/gen/openpilot/cereal/gen/cpp"

  # Fail closed: only generate what we know is used, with values taken from log.capnp itself.
  used="$(grep -rho 'cereal::[A-Za-z_]*' openpilot/common/params_keys.h openpilot/common/hardware/ | sort -u | tr '\n' ' ')"
  if [[ "$used" != "cereal::InitData cereal::LongitudinalPersonality " ]]; then
    echo "error: native params headers use cereal types this shim does not generate: $used" >&2
    exit 2
  fi
  python3 - openpilot/cereal/log.capnp "$OUT/gen/openpilot/cereal/gen/cpp/log.capnp.h" <<'EOF'
import re, sys
src = open(sys.argv[1]).read()
def enum(name, indent, pad):
  body = re.search(r'^%senum %s \{(.*?)^%s\}' % (indent, name, indent), src, re.M | re.S).group(1)
  vals = re.findall(r'^\s*([a-zA-Z0-9]+)\s*@(\d+);', body, re.M)
  # capnp C++ codegen: camelCase enumerants become UPPER_SNAKE
  return ''.join('%s%s = %s,\n' % (pad, re.sub(r'(?<!^)(?=[A-Z])', '_', n).upper(), v) for n, v in vals)
open(sys.argv[2], 'w').write(
  '// GENERATED by fork/scripts/py_tests.sh from openpilot/cereal/log.capnp. Host test shim only.\n'
  '#pragma once\n#include <cstdint>\nnamespace cereal {\n'
  'enum class LongitudinalPersonality : uint16_t {\n' + enum('LongitudinalPersonality', '', '  ') + '};\n'
  'struct InitData {\n  enum class DeviceType : uint16_t {\n' + enum('DeviceType', '  ', '    ') + '  };\n};\n'
  '}\n')
EOF
  cat > "$OUT/swaglog_stub.cc" <<'EOF'
// GENERATED by fork/scripts/py_tests.sh. Host test shim only.
#include <cstdarg>
#include <cstdio>
void cloudlog_e(int levelnum, const char *filename, int lineno, const char *func, const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);
  fprintf(stderr, "[cloudlog %d] %s:%d %s: ", levelnum, filename, lineno, func);
  vfprintf(stderr, fmt, args);
  fputc('\n', stderr);
  va_end(args);
}
EOF
  g++ -std=c++17 -O1 -fPIC -shared -I"$OUT/gen" -I. -Iopenpilot \
      -o "$LIB.tmp" "${SRCS[@]}" "$OUT/swaglog_stub.cc" -lpthread
  mv "$LIB.tmp" "$LIB"
fi

# msgq's Python extension, from the Cython-generated ipc_pyx.cpp that ships in the tree.
PYINC="$("$PY" -c 'import sysconfig; print(sysconfig.get_paths()["include"])')"
PYTAG="$("$PY" -c 'import sys; print(f"{sys.implementation.cache_tag}")')"
MSGQ="$OUT/$PYTAG/ipc_pyx.so"
if [[ ! -f "$MSGQ" ]]; then
  echo "building host msgq ipc_pyx.so ($PYTAG) -> $MSGQ"
  mkdir -p "$(dirname "$MSGQ")"
  g++ -std=c++17 -O1 -fPIC -shared -I. -Imsgq -I"$PYINC" -o "$MSGQ.tmp" "${MSGQ_SRCS[@]}" -lpthread
  mv "$MSGQ.tmp" "$MSGQ"
fi

cat > "$OUT/sitecustomize.py" <<EOF
# GENERATED by fork/scripts/py_tests.sh: load host (x86_64) builds instead of the shipped aarch64 ones.
import ctypes
import importlib.abc
import importlib.machinery
import importlib.util
import sys

_CDLL = ctypes.CDLL
class _HostCDLL(_CDLL):
  def __init__(self, name, *args, **kwargs):
    if str(name).endswith("libparams_c.so"):
      name = "$LIB"
    super().__init__(name, *args, **kwargs)
ctypes.CDLL = _HostCDLL

_EXT = {"msgq.ipc_pyx": "$MSGQ"}
class _HostExtFinder(importlib.abc.MetaPathFinder):
  def find_spec(self, fullname, path=None, target=None):
    if fullname in _EXT:
      loader = importlib.machinery.ExtensionFileLoader(fullname, _EXT[fullname])
      return importlib.util.spec_from_file_location(fullname, _EXT[fullname], loader=loader)
    return None
sys.meta_path.insert(0, _HostExtFinder())
EOF

# Isolated params store: never touch the developer's real ~/.comma or /data/params.
PARAMS_HOME="$(mktemp -d)"
trap 'rm -rf "$PARAMS_HOME"' EXIT

export PYTHONPATH="$OUT:$REPO:$REPO/opendbc_repo${PYTHONPATH:+:$PYTHONPATH}"
export HOME="$PARAMS_HOME" OPENPILOT_PREFIX="fork-py-tests-$$"
has_path=0
for a in "$@"; do [[ -e "${a%%::*}" ]] && has_path=1; done
if [[ $has_path -eq 0 ]]; then set -- "$@" "${TESTS[@]}"; fi
"$PY" -m pytest -p no:cacheprovider -q "$@"
